server.port=8086
spring.application.name=assignment-service

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/miniproject_assignment}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry:8761/eureka/}

# Cross-Service OpenFeign Client Config (Timeout handling for quizzes and grading calls)
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Gemini AI (Quiz generation)
gemini.api.key=${GEMINI_API_KEY:}
